### PR TITLE
xeger: avoid deprecated sre_parse module in python-3.11+

### PR DESCRIPTION
**Pull request by slyon**
The undocumented sre_parse module got deprecated in Python 3.11 which leads to build/test failures on Linux distributions making use of this version, e.g. Ubuntu 23.04.

See bpo-47152: https://github.com/python/cpython/issues/91308

### CODE REVIEW

**Comment by bjmc** [comment]
Thanks for this fix! Please add Python 3.11 to `tox.ini` to make sure we have test coverage for this.

**Comment by slyon** [comment]
Hmm.. looks like we need some more work on the CI: `ERROR: InterpreterNotFound: python3.11`

Do you have any hints what needs to be done here? Do we need to switch to a newer CI runner, supporting python3.11?

**Comment by bjmc** [comment]
Sounds like it. Either a newer CI runner, or get Py3.11 added to this one. This project uses https://github.com/mikicz/docker-tox-base as the Docker image for CI runs - you could add (or request) support for 3.11 there.

I'm busy now, but I can take a look at it this weekend.

**Comment by bjmc** [comment]
There's also an unrelated `mypy` failure around typing, so that needs to be fixed as well.

**Comment by slyon** [comment]
I silenced the two `mypy` errors, as those seem to be false positives to me.

It would be great if you could have a look into the `docker-tox-base` CI image, to enable `py311`, thanks!
I already applied this patch in Ubuntu (slightly modified, to match downstream sources): https://launchpad.net/ubuntu/+source/python-rstr/2.2.6-3ubuntu1

**Comment by bjmc** [comment]
>  https://launchpad.net/ubuntu/+source/python-rstr/2.2.6-3ubuntu1

This isn't rstr v2.2.6 any more - this should be at least `3.2.0` and it will probably be `3.2.1` 🙂

**Comment by slyon** [comment]
Right, that's why I backported the patch in Ubuntu. And we'll move ahead to a more recent upstream version, once the Debian mantainer decides to do so: https://tracker.debian.org/pkg/python-rstr

**Comment by bjmc** [comment]
Sorry for the delay. Thanks for your contribution @slyon! Would you like to be listed in `AUTHORS`?

**Comment by slyon** [comment]
> Sorry for the delay. Thanks for your contribution @slyon! Would you like to be listed in `AUTHORS`?

Thanks for getting it landed. No need to give credit in `AUTHORS` for this tiny "drive-by fix".

**Pull request merged**
