### PR TITLE
Statically type the whole library using PEP 484 annotations

### PR DESCRIPTION
**Pull request by pcorpet**

### CODE REVIEW

**Comment by pcorpet** [comment]
Please make sure to run CI on this PR before merging it (why is it not triggering?)

**Comment by bjmc** [comment]
> why is it not triggering?

Good question. Maybe because it's on your fork instead of this repo?

**Comment by bjmc** [comment]
I'm away on holiday until next week but I'll give it a proper review then. At a glance, this looks great. I much prefer proper inline notation to the standalone files. Thanks for this!

**Comment by bjmc** [comment]
I just found and enabled this setting on CircleCI, so I hope that will make it build your PRs.

image

**Comment by bjmc** [comment]
Sorry for the delayed response. This LGTM. Thanks for doing this!

**Comment by bjmc** [comment]
@pcorpet Would you like to be listed in `AUTHORS` when I do a new release in December?

**Comment by pcorpet** [comment]
Thanks @bjmc , sure that's cool to be mentioned.

**Pull request merged**
