### PR TITLE
Adds type hints as stubs.

### PR DESCRIPTION
**Pull request by pcorpet**

### CODE REVIEW

**Comment by pcorpet** [comment]
@bjmc Can you take a look please?

**Comment by bjmc** [comment]
Hi @pcorpet - Sorry for the slow reply, thanks for your contribution!

There was a similar PR [a little while back](https://github.com/leapfrogonline/rstr/pull/2) and my same question from that one applies here: Why not add the typing inline in the code base, rather than separate annotation files?

In my experience on other projects, devs (including myself) are much more likely to keep the typing updated and correct if it's directly inline with the code.

**Comment by pcorpet** [comment]
I've tried, but because the code is actually quite dynamic, it ended up being tricky.

Specifically having the `printable`, `letters` and other at the top level of the module being dynamically generated makes it difficult for static typing;

**Comment by bjmc** [comment]
Ah, I see what you mean. We could refactor that fairly easily. I wrote that bit years ago thinking I was being clever, but it's purely a convenience feature and could be replaced with explicit function definitions.

**Comment by pcorpet** [comment]
Alright, I'll try again. Note also that the implementation of base classes is hard to type as it is because `Xeger` and `RstrBase` are not really separated (e.g. `Xeger` uses `self._alphabets` which is defined in `RstrBase`).

Also while typing I uncovered some cornercases which needs fixing. So I'll send fixes.

**Comment by bjmc** [comment]
> not really separated (e.g. Xeger uses self._alphabets which is defined in RstrBase).

Yeah, that's a wart that could arguably stand fixing. I think I had some notion that somebody might define a non-ASCII `Xeger` subclass that inherited from a different base and used different alphabets, but to my knowledge nobody has ever done that.

**Comment by pcorpet** [comment]
Other solution proposed in #17

**Comment by bjmc** [comment]
Closed in favor of #17

**Pull request closed without merging**
