### PR TITLE
Moved the metadata into PEP 621-compliant pyproject.toml.

### PR DESCRIPTION
**Pull request by KOLANICH**
Moved the metadata into PEP 621-compliant pyproject.toml.

### CODE REVIEW

**Comment by bjmc** [comment]
Hi, can you explain a little bit about the motivation for this change? What's the advantage over `setup.cfg`?

**Comment by KOLANICH** [comment]
Also it is toml, so machine-readable and -editable.

**Comment by bjmc** [comment]
`setup.cfg` is a simple ini format.

I'm not opposed to this change, but I guess I'm [very jaded and cynical](https://xkcd.com/927/) about the ever-evolving Python packaging landscape.

I'm old enough to remember when `setuptools` was the One True New Standard Tool [to replace distuitls.](https://stackoverflow.com/questions/25337706/setuptools-vs-distutils-why-is-distutils-still-a-thing)

**Comment by bjmc** [comment]
Where is `version` specified in this?

**Comment by KOLANICH** [comment]
>I'm old enough to remember when setuptools was the One True New Standard Tool to replace distuitls.

So do I. And PEP 621 is a step into the direction of fixing all this mess.

>Where is version specified in this?

The closest tag in the format `v<major>.<minor>.<patch>` is fetched from the version control system thanks to `setuptools_scm`.

**Comment by KOLANICH** [comment]
`setup.cfg is a simple ini format.`

Not so simple. It cannot be parsed without knowledge how to parse each field and subdict. Some are arrays separated by `;`, another ones are separated by `,`, also arrays support multiline syntax for them. Some stuff are not arrays but dicts using the similar kultiline syntax; the result is: to parse it properly one needs setuptools. And BTW `ini` itself is different in different apps, so there is ain't no thing as `ini` format.

**Comment by bjmc** [comment]
Resolves #23

**Pull request merged**
